module.exports = {
  docs: [
    "welcome",
    {
      "Esmile-Useful": [
        "useful/start",
        {
          Validations: [
            "useful/validation/isEmptyString",
            "useful/validation/isValidEmail",
            "useful/validation/isValidNumber",
            "useful/validation/isValidUrl",
          ],
          Generators: ["useful/gen/generateCaptcha", "useful/gen/generateKey", "useful/gen/generatePassword"],
          Colors: ["useful/color/colorHashtag", "useful/color/colorZero", "useful/color/listLogColor"],
          Utils: [
            "useful/utils/formats",
            "useful/utils/log",
            "useful/utils/millisecond",
            "useful/utils/random",
            "useful/utils/randomItem",
            "useful/utils/symbols",
            "useful/utils/type",
            "useful/utils/wait",
          ],
        },
      ],
      "Esmile.js": [
        "client/start",
        "client/Client",
        {
          Builders: [
            {
              Slashs: [
                "client/builders/slash/Slash",
                "client/builders/slash/SlashOption",
                "client/builders/slash/SlashSubCommandGroup",
                "client/builders/slash/SlashSubCommands",
              ],
            },
            "client/builders/ButtonBuilder",
            "client/builders/ChannelSelect",
            "client/builders/EmbedBuilder",
            "client/builders/GuildMemberVerificationFields",
            "client/builders/InputText",
            "client/builders/MessageActionRow",
            "client/builders/MessageAttachment",
            "client/builders/MessageButton",
            "client/builders/MessageEmbed",
            "client/builders/Modal",
            "client/builders/RoleSelect",
            "client/builders/RowBuilder",
            "client/builders/SelectMenuBuilder",
            "client/builders/StringSelect",
            "client/builders/UserSelect",
          ],
          Managers: [
            "client/managers/ActionsManager",
            "client/managers/ApplicationCommandManager",
            "client/managers/ApplicationCommandPermissionManager",
            "client/managers/AutoModManager",
            "client/managers/BaseThreadManager",
            "client/managers/ChannelManager",
            "client/managers/EmojiManager",
            "client/managers/GuildApplicationCommandManager",
            "client/managers/GuildAutoModManager",
            "client/managers/GuildBanManager",
            "client/managers/GuildChannelManager",
            "client/managers/GuildDiscoveryManager",
            "client/managers/GuildEmojiManager",
            "client/managers/GuildIntegrationManager",
            "client/managers/GuildInviteManager",
            "client/managers/GuildManager",
            "client/managers/GuildMemberManager",
            "client/managers/GuildMemberRoleManager",
            "client/managers/GuildMemberVerificationManager",
            "client/managers/GuildPruneManager",
            "client/managers/GuildRoleManager",
            "client/managers/GuildScheduledEventManager",
            "client/managers/GuildScheduledEventUsersManager",
            "client/managers/GuildStageInstanceManager",
            "client/managers/GuildStickerManager",
            "client/managers/GuildTemplateManager",
            "client/managers/GuildVanityManager",
            "client/managers/GuildVoiceStateManager",
            "client/managers/GuildWidgetManager",
            "client/managers/PermissionOverwriteManager",
            "client/managers/PresenceManager",
            "client/managers/ReactionManager",
            "client/managers/ReactionUserManager",
            "client/managers/RoleManager",
            "client/managers/RolePromptManager",
            "client/managers/ScheduledEventManager",
            "client/managers/StageInstanceManager",
            "client/managers/StickerManager",
            "client/managers/ThreadManager",
            "client/managers/ThreadMemberManager",
            "client/managers/UserManager",
            "client/managers/VoiceStateManager",
            "client/managers/WelcomeScreenManager",
          ],
          Structures: [
            {
              Interface: [
                "client/structures/interface/Slash",
                "client/structures/interface/SlashOption",
                "client/structures/interface/SlashSubCommand",
                "client/structures/interface/SlashSubCommandGroups",
                "client/structures/interface/TextBasedChannels",
                "client/structures/interface/VoiceBasedChannels",
              ],
              Misc: ["client/structures/misc/APIGuild"],
            },
            [
              "client/structures/Activity",
              "client/structures/ApplicationCommand",
              "client/structures/ApplicationCommandInteraction",
              "client/structures/ApplicationCommandPermission",
              "client/structures/AutocompleteInteraction",
              "client/structures/BaseGuildChannel",
              "client/structures/ButtonInteraction",
              "client/structures/CategoryChannel",
              "client/structures/Channel",
              "client/structures/ClientApplication",
              "client/structures/ClientUser",
              "client/structures/CommandInteraction",
              "client/structures/CommandInteractionOptionResolver",
              "client/structures/ContextMenuInteraction",
              "client/structures/ContextMessageInteraction",
              "client/structures/ContextUserInteraction",
              "client/structures/DirectoryChannel",
              "client/structures/DMChannel",
              "client/structures/Emoji",
              "client/structures/FetchedThreads",
              "client/structures/ForumChannel",
              "client/structures/Guild",
              "client/structures/GuildAuditLog",
              "client/structures/GuildAuditLogChanges",
              "client/structures/GuildAuditLogEntry",
              "client/structures/GuildAutoMod",
              "client/structures/GuildAutoModActions",
              "client/structures/GuildBan",
              "client/structures/GuildDiscovery",
              "client/structures/GuildIntegration",
              "client/structures/GuildMember",
              "client/structures/GuildMemberVerification",
              "client/structures/GuildPreview",
              "client/structures/GuildScheduledEvent",
              "client/structures/GuildScheduledEventUser",
              "client/structures/GuildTemplate",
              "client/structures/GuildVanity",
              "client/structures/GuildWidget",
              "client/structures/GuildWidgetSettings",
              "client/structures/Interaction",
              "client/structures/InteractionWebhook",
              "client/structures/Invite",
              "client/structures/Message",
              "client/structures/MessageComponentInteraction",
              "client/structures/MessageMentions",
              "client/structures/MessageReaction",
              "client/structures/MessageReference",
              "client/structures/ModalInteraction",
              "client/structures/NewsChannel",
              "client/structures/PartialSticker",
              "client/structures/PermissionOverwrite",
              "client/structures/Presence",
              "client/structures/Role",
              "client/structures/RolePrompts",
              "client/structures/SelectMenuInteraction",
              "client/structures/StageChannel",
              "client/structures/Sticker",
              "client/structures/StickerPack",
              "client/structures/Team",
              "client/structures/TeamMember",
              "client/structures/TextChannel",
              "client/structures/ThreadChannel",
              "client/structures/ThreadMember",
              "client/structures/TriggeredAutoModRule",
              "client/structures/User",
              "client/structures/VerificationFormFields",
              "client/structures/VoiceChannel",
              "client/structures/VoiceRegion",
              "client/structures/VoiceState",
              "client/structures/Webhook",
              "client/structures/WebhookClient",
              "client/structures/WelcomeScreen",
              "client/structures/WelcomeScreenChannel",
            ],
          ],
          Util: [
            {
              Collections: ["client/util/collections/RaidenCol"],
            },
            [
              "client/util/ActivityFlags",
              "client/util/ApplicationFlags",
              "client/util/Bitfield",
              "client/util/ChannelFlags",
              "client/util/Constants",
              "client/util/DataManager",
              "client/util/EmojiResolver",
              "client/util/GuildMemberFlags",
              "client/util/Intents",
              "client/util/InvitePayload",
              "client/util/MessageFlags",
              "client/util/MessagePayload",
              "client/util/Permissions",
              "client/util/RoleFlags",
              "client/util/Snowflake",
              "client/util/StickerPayload",
              "client/util/SystemChannelFlags",
              "client/util/ThreadMemberFlags",
              "client/util/UserFlags",
              "client/util/UserPayload",
              "client/util/Util",
            ],
          ],
        },
      ],
      Builders: [
        "builders/start",
        {
          Builder: [
            "builders/builder/ButtonBuilder",
            "builders/builder/EmbedBuilder",
            "builders/builder/RowBuilder",
            "builders/builder/SelectMenuBuilder",
          ],
          Normal: ["builders/normal/Button", "builders/normal/Embed", "builders/normal/Row", "builders/normal/SelectMenu"],
          Utils: ["builders/util/ButtonStyle", "builders/util/Constants", "builders/util/Util"],
        },
      ],
      Billing: [
        {
          "Getting Started": ["billing/start/require", "billing/start/install", "billing/start/webserver", "billing/start/pterodactyl"],
        },
        {
          Upgrading: ["billing/upgrade/update"],
        },
        {
          Administration: ["billing/admin/admin-area"],
        },
        {
          Extensions: [
            "billing/extensions/intro",
            {
              Gateways: ["billing/extensions/gateways/paypal"],
            },
          ],
        },
      ],
    },
  ],
};
